### ISSUE TITLE
Rename the mpack project to mlapack or similar to avoid clashes with other programs/libraries with the same name

### ISSUE THREAD

**Issue by RaumZeit** [nakatamaho/mplapack#2]
Hi,
unfortunately, the `mpack` project name is *not unique* among Linux distributions. Most Linux distributions already provide an `mpack` or `libmpack` package that serves totally different purposes. The first provides tools for encoding/decoding MIME messages and the second is a small binary serialization/RPC library.

To circumvent the problem of multiple packages with the same name, and competition with `mpack.pc` from `libmpack` I suggest a renaming of at least some files and locations to `mlapack`. I believe this would help to make the library more popular, especially when pre-compiled binary packages are available that do not interfere with others...

I've already set up a branch with the required changes (see https://github.com/RaumZeit/mpack/tree/dev_rename) but wanted to start a discussion on that matter before actually submitting a pull request.

Best

**Comment by nakatamaho** [comment]
Hm I renamed to mplapack! thank you very much!

**Comment by nakatamaho** [comment]
Please check v0.9.0 released today
