### ISSUE TITLE
Array indexing starts at one in some functions

### ISSUE THREAD

**Issue by WBosonic** [nakatamaho/mplapack#3]
When testing Rgelss it crashed when querying the workspace.

Looking at the code I came accross this (line 167 of Rgells.cpp):
```c++
work[1] = maxwrk;
```

which should be:

```c++
work[0] = maxwrk;
```

Looking further I saw the same happining with the array of singular values, namely that `s[1]` is used as first element instead of `s[0]`.

**Comment by WBosonic** [comment]
It looks like all indexing of arrays is off.
What software was used to translate fortran to C++?
Is it feasable to manually modify the routines I need?
I'd be happy to contribute.

**Comment by entzian** [comment]
Hi WBosonic,
thanks for testing the Rgels function! From the old cvs history of the sourceforge project it looks like it was translated manually. Indices in fortran start at 1 and in c++ with 0. 
A list of all the supported functions is listed here: http://mplapack.sourceforge.net/mlapack_routines.html
Information about the updates from 2008 to 2012 is shown here: http://mplapack.sourceforge.net/

**Comment by entzian** [comment]
You could try the translation tool f2c.
f2c -C++ -C dgelss.f

**Comment by nakatamaho** [comment]
Now I fixed. Please use v.1.0.0

**Comment by nakatamaho** [comment]
Close
