### ISSUE TITLE
scl command does not work in Dockerfile_CentOS7_amd64

### ISSUE THREAD

**Issue by MacroUniverse** [nakatamaho/mplapack#63]
Hello,
in Dockerfile_CentOS7_amd64 line 7
`scl` command has no effect since it only works on the current RUN command.
To properly do this, I think you should use `SHELL [ "scl", "enable", "devtoolset-9" ]` instead. That will set the proper shell for every RUN command after.

**Comment by MacroUniverse** [comment]
You can verify this by adding `RUN g++ --version` after line 7 that it's not using version 9, but the default version of Centos7.9.2009.

**Comment by nakatamaho** [comment]
Thanks for your effort! And how about making a git pull request? It is really beneficial for me.

**Comment by MacroUniverse** [comment]
Done, please review.

**Comment by nakatamaho** [comment]
Thank you very much MacroUniverse!
https://github.com/nakatamaho/mplapack/pull/65
closing
